[package]
name = "random-ramble"
version = "0.2.0"
authors = ["Cédric Da Fonseca <dafonseca.cedric@gmail.com>"]
edition = "2021"

[dependencies]
structopt = "0.3"
serde = { version = "1.0.101", features = ["derive"] }
walkdir = "2.2.9"
rand = "0.7.3"
log = "0.4"
env_logger = "0.7"
serde_json = "1.0.47"
regex = "1"
