#+TITLE:   Random Ramble
#+DATE:    January 28, 2020
#+SINCE:   {replace with next tagged release version}
#+STARTUP: inlineimages nofold

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#maintainers][Maintainers]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]
  - [[#subcommands][SubCommands]]
    - [[#add][Add]]
    - [[#remove][Remove]]
- [[#configuration][Configuration]]
  - [[#general][General]]
    - [[#list-length][list-length]]
  - [[#themes][Themes]]
    - [[#example][Example]]
- [[#examples][Examples]]
  - [[#starts-with][Starts with]]
  - [[#specify-a-length][Specify a length]]
  - [[#specify-a-theme][Specify a theme]]
- [[#troubleshooting][Troubleshooting]]

* Description
# A summary of what this module does.

This project aims to be a simple words generator, words typically used as a
sprint name.

** Maintainers
+ @CaptainSpof (Author)

* Prerequisites
This module has no prereqisites.

* Features
# An in-depth list of features, how to use them, and their dependencies.

** SubCommands

*** Add
Adds an entry to a theme, or create a new theme

**** Examples
***** Add to an existing theme
#+BEGIN_SRC bash
rr add superheroes Batman
#+END_SRC

*** Remove
Removes an entry to a theme

**** Examples
***** Remove from an existing theme
#+BEGIN_SRC bash
rr remove superheroes Batman
#+END_SRC

* Configuration
# How to configure this module, including common problems and how to address them.

** General

*** list-length
The length of the list to be generated (default 10)

**** Example
#+BEGIN_SRC yaml
general:
  list-length: 25
#+END_SRC

** Themes
A map of values of:
key: the name of the theme
value: the path to the file containing the words

*** Example
#+BEGIN_SRC yaml
themes:
  superheroes: ./themes/superheroes.txt
  disney-characters: ./themes/disney-characters.txt
#+END_SRC

* Examples
** Starts with
Generates random words with default parameters, for words starting with 'A'
#+BEGIN_SRC bash
rr A
#+END_SRC
output:
#+BEGIN_SRC bash
Awful All-father Hercules
Abusive Abe Sapien
Abnormal Ariel
Awesome Airman
Athletic Aegis
Adorable All For One
Awkward Adam Destine
Abject Agent Mulder
Aboriginal Amunet Black
Able Aegeus
#+END_SRC

** Specify a length
Generates 3 random words with default parameters, for words starting with 'A'
#+BEGIN_SRC bash
rr A -l 3
#+END_SRC
output:
#+BEGIN_SRC bash
Absorbed Ajax
Abnormal Akron
Angelic Alexander Anderson
#+END_SRC
** Specify a theme
Generates 3 random words of theme 'animals' with default parameters, for words starting with 'A'
#+BEGIN_SRC bash
rr A -l 3 --themes animals
#+END_SRC
output:
#+BEGIN_SRC bash
Arrogant Aardvark
Apprehensive Anteater
Alive Antelope
#+END_SRC

* Troubleshooting
# Common issues and their solution, or places to look for help.
