[package]
name = "rr"
version = "0.3.0"
authors = ["Cédric Da Fonseca <dafonseca.cedric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

random-ramble = { path = "../core" }

structopt = "0.3"
serde = { version = "1.0.101", features = ["derive"] }
log = "0.4"
env_logger = "0.9"
