[package]
authors = ["Cédric Da Fonseca <dafonseca.cedric@gmail.com>"]
edition = "2018"
name = "random-ramble"
version = "0.3.0"

[dependencies]
env_logger = "0.9"
log = "0.4"
maplit = "1.0.2"
rand = "0.8.4"
regex = "1"
serde_json = "1.0.47"
thiserror = "1.0.26"
walkdir = "2.2.9"
jen = { version = "1.1", default-features = false }

[dependencies.serde]
features = ["derive"]
version = "1.0.128"

[dependencies.tera]
features = ["builtins"]
version = "1.12"

[dev-dependencies]
pretty_assertions = "0.7.2"
