[package]
name = "random-ramble"
version = "0.3.0"
authors = ["Cédric Da Fonseca <dafonseca.cedric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.2.9"
rand = "0.7.3"
log = "0.4"
env_logger = "0.7"
tera = { version = "1.12", features = ["builtins"] }
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.47"
regex = "1"
maplit = "1.0.2"
