[package]
name = "random-ramble"
version = "0.3.0"
authors = ["Cédric Da Fonseca <dafonseca.cedric@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
rand = "0.7.3"
log = "0.4"
env_logger = "0.9"
tera = "1.0.2"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.66"
regex = "1"
