name: "Update flakes"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * 0'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210415_76980a1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Make changes to pull request
        run: nix flake update
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5.0.0
        with:
          commit-message: '❄ update(flake): bump flake inputs'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: flake-updates
          delete-branch: true
          title:  '❄ update(flake): bump flake inputs'
          body: |
            ### Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
